---
# tasks file for clickable
- name: "[checking for Mac OS X dependencies]"
  include_tasks: clickable-darwin.yml
  when: "ansible_os_family == 'Darwin'"

- name: installing python dependencies
  include_role:
    name: freckles-io.install-packages
  vars:
    profile_name: base python development
    package_install_list:
      - vars:
          name: build-essential
          pkgs:
            debian:
              - build-essential
            other: omit
      - vars:
          name: build-dependencies
          pkgs:
            debian:
              - python-dev
              - python-virtualenv
              - python-pip
            redhat:
              - python-virtualenv
              - python-devel
            other: omit
